name: Hello World

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes (for testing) - CHANGE THIS LATER
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or a supported version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Hello World script
        env:
          NAME: "GitHub Actions User" # Example environment variable
        run: python main.py
